name: thesis_env
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
  - pytorch=2.4.1
  - numpy
  - matplotlib=3.9.1
  - omegaconf=2.3.0
  - wandb=0.16.6
  - hydra-core=1.3.2
  - tqdm=4.66.5
  - gymnasium=0.29.1
  - stable-baselines3=2.3.2
  - rich=13.7.1
  - sb3-contrib=2.3.0
  - plotly=5.24.0