analytical:
  batch_size: 128
  epochs: 10000
  hidden_layer_sizes: []
  learning_rate: 0.0009395146226113611
  lstm_hidden_size: 256
  lstm_num_layers: 1
  num_hidden_layer: 0
  optimizer: SGD
  output_type: TwoPeakNormalLstmDistrNetwork
  problems_per_epoch: 1792
  testing_interval: 20000
stb3:
  activation_fn_name: relu
  batch_size: 64
  clip_range: 0.1
  enable_critic_lstm: true
  ent_coef: 0.032400016123457165
  epochs: 10
  gae_lambda: 0.92
  gamma: 0.0
  learning_rate: 2.2568175267734592e-05
  log_std_init: -0.40918312871720075
  lr_schedule: constant
  lstm_hidden_size: 256
  max_grad_norm: 0.5
  n_envs: 1
  n_steps: 512
  net_arch_type: medium
  non_recurrent_policy: MlpPolicy
  norm_advantages: true
  ortho_init: true
  recurrent_policy: MlpLstmPolicy
  testing_interval: 1000000
  total_timesteps: 65000000
  use_recurrent_policy: false
  vf_coef: 0.8129608941298637
