defaults:
  - hyperparams: hyperparams
  - logging : logging_params
  - vis : vis_params
  - optuna : optuna_params
  - _self_

random_seed: 42

use_stb3: false
do_vis: false
use_optuna: false

server_postfix: "" # :1 for the first server, "" for local execution
torch_num_threads: 1

save_trained_model: true
model_save_dir: "model_saves_files_perf_direct" # Directory the models are saved to

# Problem Generation Parameter
number_of_joints: 2
tolerable_accuracy_error: 0.01 # The tolerance in accuracy that is still regarded as correct
parameter_convention: "DH"
min_link_length: 0.3
max_link_length: 0.5

number_of_test_problems: 5000 # Number of test problems to generate
