defaults:
- hyperparams: hyperparams
- logging: logging_params
- vis: vis_params
- optuna: optuna_params
- _self_
do_vis: false
max_link_length: 0.5
min_link_length: 0.3
model_save_dir: outputs/model_save_files/benchmark/TwoPeakNormalLstmDistrNetwork/dof3
number_of_joints: 3
number_of_test_problems: 10000
parameter_convention: DH
random_seed: 42
save_trained_model: true
server_postfix: ''
tolerable_accuracy_error: 0.01
torch_num_threads: 1
use_optuna: false
use_stb3: false
