hyperparams:
  project_name: thesis-pt-02

  random_seed: 42

  use_stable_baselines3: true
  # Stable Baselines 3 parameters
  policy: "MlpPolicy"
  n_envs: 1
  # TODO random seed nutzen
  # TODO mit paramter spielen
  # TODO 128
  n_steps: 32
  # TODO 100...* n_steps = total_timesteps
  total_timesteps: 50000

  # Model architecture
  num_layer: 5
  layer_sizes: [ 64, 512, 256, 64 ]

  # Model learning parameter
  learning_rate: 1e-3
  dataset_length: 1
  batch_size: 64 # When using stable baselines, the batch size should be a factor of `n_steps * n_envs`
  epochs: 10

  testing_interval: 100 # Number of epochs to be run after which a test run is performed

  # Problem Generation Parameter
  number_of_joints: 2
  tolerable_accuracy_error: 1 # The tolerance in accuracy that is still regarded as correct
  parameter_convention: DH
  min_link_length: 1.
  max_link_length: 20.

  #Logging
  log_in_wandb: true
  log_in_console: false
  log_verbosity: 0

  visualization:
    do_visualization: false
    interval: 2000
    default_line_transparency: 1.
    frame_size_scalar: 1.1
    default_line_width: 1.5
    use_color_per_robot: false
    use_gradual_transparency: true
    standard_size: true
    save_to_file: false
    show_plot: true
    show_joint_label: false
    plot_all_in_one: true
