hyperparams:
  project_name: bachelor-thesis-prototype-01
  learning_rate: 1e-3
  batch_size: 64
  epochs: 50
  testing_interval: 5             # Number of epochs to be run after which a test run is performed
  dataset_length: 10000
  number_of_joints: 2
  log_in_wandb: false
  tolerable_accuracy_error: 0.1   # The tolerance in accuracy that is still regarded as correct
  parameter_convention: DH
  min_link_length: 0.1
  max_link_length: 20.
  visualization:
    do_visualization: true
    interval: 10
    default_line_transparency: 1.
    frame_size_scalar: 1.1
    default_line_width: 1.5
    use_color_per_robot: true
    standard_size: false
    save_to_file: false
    show_plot: true
    show_joint_label: true
