hyperparams:
  project_name: bachelor-thesis-prototype-01

  # Model architecture
  num_layer: 5
  layer_sizes: [64, 512, 256, 64]

  # Model learning parameter
  learning_rate: 1e-3
  dataset_length: 10000
  batch_size: 128
  epochs: 10

  testing_interval: 10             # Number of epochs to be run after which a test run is performed

  # Problem Generation Parameter
  number_of_joints: 2
  tolerable_accuracy_error: 0.5   # The tolerance in accuracy that is still regarded as correct
  parameter_convention: DH
  min_link_length: 1.
  max_link_length: 20.

  #Logging
  log_in_wandb: false
  log_in_console: false

  visualization:
    do_visualization: false
    interval: 5
    default_line_transparency: 1.
    frame_size_scalar: 1.1
    default_line_width: 1.5
    use_color_per_robot: true
    standard_size: true
    save_to_file: false
    show_plot: true
    show_joint_label: false
    plot_all_in_one: false
